### ISSUE TITLE
Change same-player score behaviour

### ISSUE THREAD

**Issue by one-two** [brunodrugowick/at-the-tsbyss-leaderboard#6]
Can the player name be an unique value and the score and killedby be updated when a higher score is achieved? 

Reason: After winning, players can keep on going on higher difficulties, but the winscreen POST must be sent anyway coz they can not want to keep playing.

**Comment by brunodrugowick** [comment]
Got it.

But that would allow for scores to be overwritten by anyone using the same name, not only the player which is still playing. Just stating that, because this is not necessarily a problem, given that is possible already.

My point is that IF you want to update the same score that was already created on a "game session" (let's call it that) shouldn't this "game session" on the frontend to have an information about the score it should update and then PUT instead of POSTing in this case?

Otherwise, different "game sessions" with the same player name would cause probably undesirable updates.

**Comment by brunodrugowick** [comment]
OPTION: why not allowing for the same name to be used but creating another field that references the "game session" which is unique on the frontend and then, when POSTing, that value would be used to update the same "game session" score.

Still, we have to decide if this logic should be on the back or frontend...

**Comment by one-two** [comment]
The idea was to each person keep his highest score. As for my idea, it would be possible, but doesn't make sense to play the same name and give a better score to someone else. But for now, this would be nice and would keep it clean some stuff there.

i mean, for now.

**Comment by brunodrugowick** [comment]
Got it. We handle the names later with authentication, maybe. 

Just to clarify a few more questions:

1. Should I keep only one score per name?
2. If Yes for 1, should I keep only the highest score? 

If Yes, I'd add a verification to only create the score when it's higher than the previous.
If No, this would be "latest score" not "high score".

**Comment by one-two** [comment]
1. Yes
2. Yes

Every game over screen will send a post. The player can keep playing after winning, so one playthrough can have multiple posts.

**Comment by brunodrugowick** [comment]
Ok. Will do it.

Just being thorough:

- When deploying this modification, should I updated the current scores accordingly on the database (i.e., keep only the highest score for each name)?

**Comment by one-two** [comment]
Yeah, sure.

**Comment by brunodrugowick** [comment]
Great. Let me know if there's any other cleanup I should do on the database because I'll remove for now two functions of the API:

- PUT on /api/score/:id - because I'll handle the modifications when you POST a new score.
- DELETE on /api/score/:id - let's just not allow it via API for now.

**Comment by brunodrugowick** [comment]
@one-two, a gente fala in english aqui por que, mesmo? Hahahahaha

**Comment by brunodrugowick** [comment]
I'm having issues with quick subsequent requests. The second request doesn't seem to find the existent score (it is there!) and creates a new one.

I'll take a look at transactions: https://mongoosejs.com/docs/transactions.html

**Comment by brunodrugowick** [comment]
My first approach was something like this: https://stackoverflow.com/questions/48964943/mongoose-find-execute-logic-then-update-on-the-same-collection
